### ISSUE TITLE
Can't install or get it to run

### ISSUE THREAD

**Issue by bklik** [davatron5000/a11y-nutrition-cards#1]
My guess is there is a whole host of instructions missing from this README.md to actually get this to work. None of the commands listed worked. Probably because I don't have the tooling needed.

I looked up the `bundle` command. Not sure what that goes with. Tried looking on npm, and found npm-bundle. That didn't work.

Jekyll, was mentioned. I looked that up, and it looks like a Ruby something-or-other. So, I installed Ruby. Then, I installed Jekyll. After installing, I tried the `bundle` commands again. Now I get the following errors:

> Could not locate Gemfile
> Could not locate Gemfile or .bundle/ directory

I'm assuming I'm closer to getting this to work, but am still missing something.

Recommendations:

- Fix the README.md include all the missing tooling installations required
- Or, remove all the tooling cruft, and just use basic HTML/JS to make this project more accessible.

**Comment by davatron5000** [comment]
Sorry about that! The `Gemfile` wasn't actually needed after I finished the docs. You should be able to do this to get it working with this:

```
gem install jekyll
jekyll serve --livereload
```

Hopefully that unblocks you. The site is built with Jekyll on GitHub Pages which allows us to focus on content in Markdown/YAML. That's not a feature I'm interested in giving up at this point, so it'll remain Jekyll for awhile.
